### ISSUE TITLE
No sending data to UDP server

### ISSUE THREAD

**Issue by prakasa-tkpd** [log4js-node/logstashUDP#5]
Problem when try using this. No data sent to my UDP server. Following basic config like docs.

**Comment by nomiddlename** [comment]
Hard to say what's going wrong here. Any firewalls between your log4js app and the log stash server? Perhaps UDP packets are being blocked. You can use `netstat` to see if log4js is opening a socket to the server. Tools like wireshark can inspect traffic to see if packets are being sent. Running your log4js app with the environment variable `DEBUG="log4js:logstashUDP"` will output information whenever it sends data over UDP. Any errors should also be going to `console.error` by default.

**Comment by prakasa-tkpd** [comment]
close, sorry for duplicate issue in the other side :D . I have problem when try to patching this to koa middlewware. But now its done.

Actually, we still one problem here. The latest code published in npm registry different with the code base on this repository. I mean, we miss `extraDataProvider` handler. Please, republish to npm. Thanks for this awesome appender.
