### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by chumanhquang** [log4js-node/logstashUDP#8]
TypeError: Converting circular structure to JSON\n    at JSON.stringify (<anonymous>)\n    at sendLog (/Users/local/Work/03.Sources/server/source/node_modules/@log4js-node/logstashudp/src/index.js:9:35)

Line 9 (@log4js-node/logstashudp/src/index.js) : 
const buffer = Buffer.from(JSON.stringify(logObject));

**Comment by nomiddlename** [comment]
fix published to npm in logstashUDP@1.2.1 - please re-open this issue if it does not fix your problem.
